{% set name = "sphinx-tags" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphinx_tags-{{ version }}.tar.gz
  sha256: 3065219bacf47567c706f2237d5665b22f3a5167367b4c4568bcda4371a5359d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - sphinx >=5.1

test:
  imports:
    - sphinx_tags
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/sphinx-tags/
  summary: Sphinx extension to create tags for documentation pages.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melissawm
    - ocefpaf
