{% set name = "sphinx-tags" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-tags-{{ version }}.tar.gz
  sha256: 355fa0f6cf26704f0710047d2f7e8dfd9a5a79f6657f2df5014feecbf259ea04

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - flit-core >=3.2,<4
  run:
    - python >=3.6
    - sphinx >4
    - pre-commit

test:
  imports:
    - sphinx_tags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sphinx-tags/
  summary: Sphinx extension to create tags for documentation pages.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melissawm
    - ocefpaf
